// <auto-generated />
namespace NT_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FirstStep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstStep));
        
        string IMigrationMetadata.Id
        {
            get { return "201908061301509_FirstStep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
